# Generated by Django 5.1.2 on 2024-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="_options",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="multiplechoicequestion",
            name="correct_answer",
            field=models.TextField(),
        ),
    ]
